let
  sources = import ./nix/sources.nix; # Path to sources.nix generated by niv
  pkgs = import sources.nixpkgs {};
in
pkgs.mkShell {
  buildInputs = [
    pkgs.cabal-install
    pkgs.ghc
    pkgs.stack
    pkgs.neovim
    pkgs.fzf
    pkgs.git
    pkgs.nodejs
    pkgs.haskellPackages.haskell-language-server
    pkgs.more
  ];
  shellHook = ''
    # Add any additional shell setup commands here
  '';
}
